version: '3.3'

services:
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      infra:

  iioat:
    image: ignitial/iioat:1.0.0
    container_name: iioat
    ports:
      - "8080:8080"
    volumes:
      - /home/${USER}/Documents/Projects/iio/templates/app-material-template:/opt/iioat
    environment:
      - NODE_ENV=production
      - IIOS_SERVER_PORT=8080
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_REDIS_HOST=redis
      - IIOS_S3_ENDPOINT=${IIOS_S3_ENDPOINT}
      - IIOS_S3_PORT=${IIOS_S3_PORT}
      - IIOS_S3_BUCKET=${IIOS_S3_BUCKET}
      - IIOS_S3_SECURE=${IIOS_S3_SECURE}
      - IIOS_S3_ACCESS_KEY_ID=${IIOS_S3_ACCESS_KEY_ID}
      - IIOS_S3_SECRET_ACCESS_KEY=${IIOS_S3_SECRET_ACCESS_KEY}
      - IIOS_EMAILER_SMTP_USER=support@ignitial.fr
      - IIOS_EMAILER_SMTP_HOST=mail.gandi.net
      - IIOS_EMAILER_SMTP_PORT=587
      - IIOS_EMAILER_SMTP_PASS=${IIOS_EMAILER_SMTP_PASS}
    networks:
      infra:

  dlake:
    image: ignitial/dlake
    container_name: dlake
    ports:
      - "20989-20999:20989-20999"
    environment:
      - IIOS_REDIS_HOST=redis
      - IIOS_MONGODB_URI=mongodb://mongo:27017
      - IIOS_DBNAME=${IIOS_DBNAME}
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=dlake
      - IIOS_SERVER_PORT=20991
    networks:
      infra:

  auth:
    image: ignitial/auth
    container_name: auth
    ports:
      - "20199:20199"
    environment:
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=auth
      - IIOS_SERVER_PORT=20199
    networks:
      infra:

  lambda:
    image: ignitial/lambda:${SVC_VERSION}
    container_name: lambda
    volumes:
      - ${PWD}:/opt/lambda
    ports:
      - ${IIOS_LAMBDA_EXPORTED_PORTS}
    environment:
      - IIOS_SERVER_HOST_TEST=${IIOS_SERVER_HOST_TEST}
      - IIOS_DOCKER_REGISTRY=localhost:5001
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=${IIOS_SERVER_HOST}
      - IIOS_SERVER_PORT=${IIOS_SERVER_PORT}
    networks:
      infra:

  # registry:
  #   image: registry:2
  #   container_name: registry
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     infra:
  #
  # dind:
  #   image: docker:dind
  #   privileged: true
  #   container_name: dind
  #   environment:
  #     - DOCKER_TLS_CERTDIR=
  #   networks:
  #     infra:

  docker:
    image: ignitial/docker:${SVC_VERSION}
    container_name: docker
    ports:
      - ${IIOS_DOCKER_EXPORTED_PORTS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${USER}/Documents/Projects/iio/services/docker:/opt/docker
    environment:
      # force host docker use
      - IIOS_DOCKER_SOCKET_PATH=/var/run/docker.sock
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=docker
      - IIOS_SERVER_PORT=${IIOS_DOCKER_SERVER_PORT}
    networks:
      infra:

networks:
  infra:
    external: true
