version: '3.3'

services:
  lambda:
    image: ignitial/lambda:${SVC_VERSION}
    container_name: lambda
    ports:
      - ${IIOS_LAMBDA_EXPORTED_PORTS}
    environment:
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=lambda
      - IIOS_SERVER_PORT=${IIOS_SERVER_PORT}
    networks:
      infra:

networks:
  infra:
    external: true
